
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace JuSha.Framework.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Func
{

    public int ID { get; set; }

    public string FuncName { get; set; }

    public Nullable<int> ParentId { get; set; }

    public int FuncType { get; set; }

    public string Url { get; set; }

    public int CreateUser { get; set; }

    public System.DateTime CreateTime { get; set; }

    public int UpdateUser { get; set; }

    public System.DateTime UpdateTime { get; set; }

    public int IsDelete { get; set; }

}

}
